<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: sans-serif;
            font-size: 8px;
            margin: 0;
            padding: 0;
        }

        .footer {
            width: 100%;
            text-align: center;
            border-top: 1px solid #aaa;
            padding-top: 5px;
        }

        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }

        .left {
            float: left;
        }

        .center {
            text-align: center;
            display: inline-block;
        }

        .right {
            float: right;
        }
    </style>
</head>

<body>
    <div class="footer clearfix"
        style="font-size:10px; width:100%; text-align:center; border-top:1px solid #aaa; padding-top:5px;">
        <div class="left" style="float:left;">Generated by: {{ $generatedBy }}</div>
        <div class="center" style="display:inline-block;">Page [page] of [topage]</div>
        <div class="right" style="float:right;">Generated on: {{ now()->format('M d, Y, h:i A') }}</div>
    </div>
</body>
</html>
